### ISSUE TITLE
S1. Que el nodo pueda enviar datos a traves de WiFi

### ISSUE THREAD

**Issue by cristianfunes79** [cristianfunes79/emi#10]
Epic: #6 

### Description
Agregar soporte para conectarse a una red WiFi y para poder enviar datos a traves de un socket.

### Tasks
- [ ] Agregar soporte para conectarse a WiFi con SSID y PASS preconfigurados.
- [ ] Agregar soporte para enviar datos a IP:PUERTO preconfigurados.
- [ ] Agregar soporte para envio de temperatura.
