### ISSUE TITLE
S2. Que el monitor pueda enviar SMS

### ISSUE THREAD

**Issue by cristianfunes79** [cristianfunes79/emi#14]
Epic: #6 

### Description
Agregar soporte para envio de SMS usando el modem SIM800. 

### Tasks
- [ ] Realizar pruebas de comunicacion con el modem SIM800.
- [ ] Agregar soporte para envio de SMS con SIM800.
- [ ] Crear biblioteca con funciones basicas para el manejo del modem SIM800.
