### ISSUE TITLE
S3. Que el monitor pueda recibir temperatura por WiFi

### ISSUE THREAD

**Issue by cristianfunes79** [cristianfunes79/emi#18]
Epic: #6 

### Description
Agregar soporte para que el monitor se comporte como un servidor que se conecte a una Red WiFi con una SSID y PASS preconfigurados, y que escuche por conexiones entrantes a una IP:PUERTO preconfigurados. Cuando la temperatura sobrepase el limite, debe generar una alerta.

### Tasks
- [ ] Agregar soporte para conectarse a SSID y PASS preconfigurados.
- [ ] Agregar soporte para server en IP y PUERTO preconfigurados.
- [ ] Agregar soporte para parseo de tramas de temeperatura.
- [ ] Agregar soporte para alerta de temperatura fuera de rango en rangos preconfigurados.
- [ ] Agregar soporte para envio de alerta por SMS a telefono preconfigurado.
